app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 18000000

server:
   port: 8091

#eureka:
#  instance:
#    hostname: binar-cinema-discovery.up.railway.app
#  client:
#    serviceUrl:
#      defaultZone: https://${eureka.instance.hostname}/eureka
      
spring:
   application:
     name: auth-service
   jpa:
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:postgresql://containers-us-west-150.railway.app:7518/railway
     username: postgres
     password: BkG8bMdqgMqagg2qZZ7R
     driver-class-name: org.postgresql.Driver
