app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 18000000

server:
   port: 8080

eureka:
  instance:
    hostname: binar-cinema-discovery.up.railway.app
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${{ CINEMA_DISCOVERY_SERVER }}/eureka
      
spring:
   application:
     name: auth-service
   jpa:
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:postgresql://:@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}
     username: ${{ PGUSER }}
     password: ${{ PGPASSWORD }}
     driver-class-name: org.postgresql.Driver
