app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 18000000

server:
   port: 8091

#eureka:
#  instance:
#    hostname: binar-cinema-discovery.up.railway.app
#  client:
#    serviceUrl:
#      defaultZone: https://${eureka.instance.hostname}/eureka
      
spring:
   application:
     name: auth-service
   jpa:
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:postgresql://localhost:5432/bioskop_db
#     url: jdbc:postgresql://containers-us-west-54.railway.app:6873/railway
     username: postgres
     password: password
#     password: PrAVTvYhJtOAf4je4d9B
     driver-class-name: org.postgresql.Driver
