app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
    exp: 18000000

# server:
#   port: 8082

eureka:
  instance:
    hostname: cinema-discovery-server.up.railway.app
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/
      registerWithEureka: true
      fetchRegistry: true
  
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://cinema-discovery-server.up.railway.app:8888

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://containers-us-west-113.railway.app:6613/railway
    username: postgres
    password: AreLJxqASMsvIf3xhbN4
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
     web:
       exposure:
         include: '*'


#   jpa:
#     hibernate:
#       ddl-auto: update
#   datasource:
#     url: jdbc:postgresql://localhost:5432/bioskop_db
#     # jdbc:postgresql://containers-us-west-68.railway.app:6368/railway
#     # password : xhtTI10rPJkQvUXUpfVz
#     username: postgres
#     password: password
#     driver-class-name: org.postgresql.Driver